DROP TABLE IF EXISTS dogs;
  
CREATE TABLE dogs (
id INT NOT NULL,
name VARCHAR(250) NOT NULL,
age INT NOT NULL
);

DROP TABLE IF EXISTS book;

CREATE TABLE book (
id INT NOT NULL PRIMARY KEY,
bookname VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
id INT NOT NULL PRIMARY KEY,
name VARCHAR(250) NOT NULL,
email VARCHAR(250) NOT NULL,
role VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS BookUser;

CREATE TABLE BookUser (
 bookid INT NOT NULL PRIMARY KEY ,
 userid INT NOT NULL ,
 FOREIGN KEY (bookid) REFERENCES book(id) ON DELETE CASCADE,
 FOREIGN KEY (userid) REFERENCES Users(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Security;

CREATE TABLE Security(
 id INT NOT NULL PRIMARY KEY,
 isin INT NOT NULL,
 cusip INT NOT NULL, 
 issuer INT NOT NULL,
 maturitydate DATE NOT NULL,
 coupon INT NOT NULL,
 type VARCHAR(250) NOT NULL,
 facevalue INT NOT NULL,
 status VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS Counterparty;

CREATE TABLE Counterparty(
 id INT NOT NULL PRIMARY KEY,
 name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS Trade;

CREATE TABLE Trade(
 id INT NOT NULL PRIMARY KEY,
 bookid INT NOT NULL,
 counterpartyid INT NOT NULL,
 securityid INT NOT NULL,
 quantity INT NOT NULL,
 status VARCHAR(250) NOT NULL,
 price INT NOT NULL,
 buysell VARCHAR(250) NOT NULL,
 tradedate DATE NOT NULL,
 settlementdate DATE NOT NULL,
 FOREIGN KEY(bookid) REFERENCES book(id) ON DELETE CASCADE,
 FOREIGN KEY(counterpartyid) REFERENCES counterparty(id) ON DELETE CASCADE,
 FOREIGN KEY(securityid) REFERENCES security(id) ON DELETE CASCADE
);
